server: 
 port: 10086

sms: 
 monyun: 
  url: http://tsc1.800ct.com:8803/sms/v2/std/single_send
  userid: ENC(GUSorkAcOLLcgI3s+5MWQw==)
  pwd: ENC(bSbrjR91bL2TLuISJpstVQ==)

spring:
 profiles: 
  active: local
 mail: 
  host: smtp.cndi.com
  port: 25
  username: ENC(2I5W/FqT88Leq4cdcKp72lA/Sn8MJsYW)
  password: ENC(S+r5VbJjcn7i3eot22chwRiLqOggV0l9)
  properties: 
   mail:
    smtp: 
     auth: true
     starttls: 
      enable: true
      required: true
     socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      
system:
 name: "BWZB"
 
wechat:
  webhook: ENC(Q8xybI7pSS9QYd1j38PYe01j3T+K/XWabBlmXFtQcCaaUKYyRHP9BqXNZ4u1TzDL)
# webhook: ENC(CIbOut3fy1/P1xbRRMKOc7/1Ckf8rsWpRp7Xq4IcT/0nmHgTh7x2HYMn/HYC0QbN)
